# Generated by Django 2.2.1 on 2019-10-02 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=26, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264, unique=True)),
                ('entity', models.CharField(max_length=264, unique=True)),
                ('role', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TM_APP.comments')),
                ('id', models.ManyToManyField(to='TM_APP.users')),
            ],
        ),
    ]
