# Generated by Django 2.2.1 on 2019-10-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM_APP', '0002_auto_20191007_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
