# Generated by Django 2.2.1 on 2019-10-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM_APP', '0003_answers_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=264),
        ),
    ]
