# Generated by Django 2.2.1 on 2019-10-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM_APP', '0004_auto_20191007_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
